services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: 1
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./trading:/app/trading
      - ./logs:/app/logs
    env_file:
      - .env
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: 1
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
