version: '3'
services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
      - ./tests:/app/tests
      - ./logs:/app/logs
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
    command: uvicorn backend.app.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm start
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
